

SHOW DATABASES;
CREATE DATABASE LND_GEN;
GRANT ALL PRIVILEGES ON *.* TO 'etl'  


-- CREATE TABLE LND_GEN.LND_Name(Name varchar(255));
-- 
-- SELECT * FROM LND_GEN.LND_Name
-- 
-- CREATE TABLE LND_GEN.LND_Anime_JSON(Name TEXT);
-- 
-- 
--  LOAD DATA  INFILE '/var/lib/mysql-files/name.csv' 
--  INTO TABLE LND_GEN.LND_Name  
--  FIELDS TERMINATED BY ',' 
--  LINES TERMINATED BY '\n'
--  
--  
-- SHOW VARIABLES LIKE "secure_file_priv"
-- 
-- LOAD DATA LOCAL INFILE 'C:/Users/Metac/Downloads/python-code/extrt1.json' 
-- INTO TABLE LND_GEN.LND_Anime_JSON  
-- FIELDS TERMINATED BY '||||' 
-- LINES TERMINATED BY '||||||'
-- ;


